# Generated by Django 3.2.7 on 2021-09-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interest', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notified',
            name='interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.interest'),
        ),
    ]
